"use client";

import {
  Download,
  FileCode2,
  FileImage,
  Sparkles,
  UploadCloud,
  Wand2,
} from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { toast } from "sonner";

import { CodeEditor } from "@/components/tools/code-editor";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { CopyButton } from "@/components/ui/copy-button";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { downloadTextFile } from "@/lib/utils";

type SvgOptimizeOptions = {
  removeMetadata: boolean;
  simplifyPaths: boolean;
  roundDecimals: boolean;
  prettify: boolean;
  precision: number;
};

type SvgOptimizeResponse = {
  optimizedSvg: string;
  reactComponent: string;
  originalBytes: number;
  optimizedBytes: number;
  savingsPercent: number;
  elapsedMs: number;
};

const defaultSvg = `<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
  <metadata>Generated by DevToolbox</metadata>
  <path d="M128 24C74.17 24 32 48.6 32 80V176C32 207.4 74.17 232 128 232S224 207.4 224 176V80C224 48.6 181.83 24 128 24Z" fill="#FFD600"/>
  <circle cx="128.0000" cy="128.0000" r="64.0000" fill="black" fill-opacity="0.1"/>
</svg>`;

const defaultOptions: SvgOptimizeOptions = {
  removeMetadata: true,
  simplifyPaths: true,
  roundDecimals: true,
  prettify: false,
  precision: 2,
};

function formatBytes(value: number) {
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  return `${(value / (1024 * 1024)).toFixed(2)} MB`;
}

function bytesOf(text: string) {
  return new TextEncoder().encode(text).length;
}

function looksLikeSvg(value: string) {
  return /<svg[\s>]/i.test(value);
}

export function SvgOptimizerTool() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [sourceSvg, setSourceSvg] = useState(defaultSvg);
  const [result, setResult] = useState<SvgOptimizeResponse | null>(null);
  const [options, setOptions] = useState<SvgOptimizeOptions>(defaultOptions);
  const [loading, setLoading] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [outputMode, setOutputMode] = useState<"svg" | "react">("svg");

  const activeSvg = result?.optimizedSvg || sourceSvg;
  const previewDataUri = useMemo(() => {
    if (!looksLikeSvg(activeSvg)) return "";
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(activeSvg)}`;
  }, [activeSvg]);

  const originalBytes = result?.originalBytes ?? bytesOf(sourceSvg);
  const optimizedBytes = result?.optimizedBytes ?? bytesOf(activeSvg);
  const savingsPercent = result?.savingsPercent ?? 0;
  const elapsedMs = result?.elapsedMs ?? 0;

  const setOption = <T extends keyof SvgOptimizeOptions>(
    key: T,
    value: SvgOptimizeOptions[T],
  ) => {
    setOptions((prev) => ({ ...prev, [key]: value }));
  };

  const loadSvgFile = async (file: File) => {
    try {
      const text = await file.text();

      if (!looksLikeSvg(text)) {
        setError("Selected file is not a valid SVG");
        return;
      }

      setSourceSvg(text);
      setResult(null);
      setError(null);
      toast.success(`Loaded ${file.name}`);
    } catch {
      setError("Could not read SVG file");
    }
  };

  const optimizeSvg = async () => {
    setLoading(true);
    setError(null);

    try {
      if (!looksLikeSvg(sourceSvg)) {
        setError("Input must contain a valid SVG");
        return;
      }

      const response = await fetch("/api/svg-optimize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ svg: sourceSvg, options }),
      });

      const data = (await response.json()) as SvgOptimizeResponse | { error?: string };

      if (!response.ok || !("optimizedSvg" in data)) {
        setError(("error" in data && data.error) || "Optimization failed");
        return;
      }

      setResult(data);
      toast.success("SVG optimized");
    } catch {
      setError("Could not optimize SVG");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[1.05fr_1fr]">
        <div className="space-y-6">
          <Card className="p-4">
            <div
              className={`rounded-xl border-[3px] border-dashed p-8 text-center transition-colors ${
                dragging ? "border-yellow bg-yellow/10" : "border-black bg-slate-900"
              }`}
              onDragOver={(event) => {
                event.preventDefault();
                setDragging(true);
              }}
              onDragLeave={() => setDragging(false)}
              onDrop={(event) => {
                event.preventDefault();
                setDragging(false);
                const file = event.dataTransfer.files?.[0];
                if (file) {
                  void loadSvgFile(file);
                }
              }}
            >
              <UploadCloud className="mx-auto h-12 w-12 text-yellow" />
              <p className="mt-3 text-lg font-black text-white">
                Drag and drop SVG or select from your device
              </p>
              <p className="mt-1 text-sm font-semibold text-slate-300">
                Optimize for web performance and bundle size
              </p>
              <div className="mt-5 flex flex-wrap items-center justify-center gap-2">
                <Button variant="yellow" onClick={() => fileInputRef.current?.click()}>
                  <FileImage className="h-4 w-4" /> Select File
                </Button>
                <Button variant="green" onClick={() => void optimizeSvg()} disabled={loading}>
                  {loading ? <LoadingSpinner /> : <Wand2 className="h-4 w-4" />} Optimize
                </Button>
              </div>
              <input
                ref={fileInputRef}
                className="hidden"
                type="file"
                accept=".svg,image/svg+xml"
                onChange={(event) => {
                  const file = event.target.files?.[0];
                  if (file) {
                    void loadSvgFile(file);
                  }
                  event.currentTarget.value = "";
                }}
              />
            </div>
            {error ? (
              <p className="mt-4 rounded-xl border-[3px] border-black bg-coral p-3 text-sm font-bold text-black">
                {error}
              </p>
            ) : null}
          </Card>

          <Card className="overflow-hidden">
            <div className="flex items-center justify-between border-b-[3px] border-black bg-slate-900 px-4 py-3">
              <p className="text-sm font-black uppercase text-slate-200">Input SVG</p>
              <CopyButton text={sourceSvg} label="Copy Input" />
            </div>
            <CodeEditor value={sourceSvg} onChange={setSourceSvg} language="xml" height="320px" />
          </Card>

          <Card className="p-4">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="font-display text-xl font-black text-white">Optimization Settings</h3>
              <Badge variant="blue">Precision: {options.precision}</Badge>
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              <label className="flex cursor-pointer items-center justify-between rounded-xl border-[3px] border-black bg-slate-900 px-3 py-3">
                <span className="text-sm font-black text-slate-100">Remove Metadata</span>
                <input
                  type="checkbox"
                  className="h-4 w-4 accent-green"
                  checked={options.removeMetadata}
                  onChange={(event) => setOption("removeMetadata", event.target.checked)}
                />
              </label>
              <label className="flex cursor-pointer items-center justify-between rounded-xl border-[3px] border-black bg-slate-900 px-3 py-3">
                <span className="text-sm font-black text-slate-100">Simplify Paths</span>
                <input
                  type="checkbox"
                  className="h-4 w-4 accent-green"
                  checked={options.simplifyPaths}
                  onChange={(event) => setOption("simplifyPaths", event.target.checked)}
                />
              </label>
              <label className="flex cursor-pointer items-center justify-between rounded-xl border-[3px] border-black bg-slate-900 px-3 py-3">
                <span className="text-sm font-black text-slate-100">Round Decimals</span>
                <input
                  type="checkbox"
                  className="h-4 w-4 accent-green"
                  checked={options.roundDecimals}
                  onChange={(event) => setOption("roundDecimals", event.target.checked)}
                />
              </label>
              <label className="flex cursor-pointer items-center justify-between rounded-xl border-[3px] border-black bg-slate-900 px-3 py-3">
                <span className="text-sm font-black text-slate-100">Prettify Code</span>
                <input
                  type="checkbox"
                  className="h-4 w-4 accent-green"
                  checked={options.prettify}
                  onChange={(event) => setOption("prettify", event.target.checked)}
                />
              </label>
            </div>

            <div className="mt-5">
              <label className="mb-2 block text-xs font-black uppercase text-slate-300">
                Precision
              </label>
              <input
                type="range"
                min={0}
                max={6}
                step={1}
                value={options.precision}
                onChange={(event) => setOption("precision", Number(event.target.value))}
                className="h-3 w-full cursor-pointer rounded-lg border-[3px] border-black bg-slate-200 accent-black"
              />
              <div className="mt-1 flex justify-between text-[10px] font-black uppercase text-slate-400">
                <span>Draft</span>
                <span>Balanced</span>
                <span>Exact</span>
              </div>
            </div>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="overflow-hidden">
            <div className="flex items-center justify-between border-b-[3px] border-black bg-slate-900 px-4 py-3">
              <p className="text-sm font-black uppercase text-slate-200">Optimized Preview</p>
              <Badge variant="green">{result ? `${elapsedMs}ms` : "Ready"}</Badge>
            </div>
            <div className="bg-[radial-gradient(circle,rgba(148,163,184,0.4)_1px,transparent_1px)] bg-[length:18px_18px] p-8">
              <div className="mx-auto flex h-[300px] max-w-[300px] items-center justify-center rounded-xl border-[3px] border-black bg-white p-6 shadow-brutal">
                {previewDataUri ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    alt="SVG Preview"
                    src={previewDataUri}
                    className="h-full w-full object-contain"
                  />
                ) : (
                  <p className="text-center text-sm font-bold text-slate-500">No preview available</p>
                )}
              </div>
            </div>
          </Card>

          <div className="grid gap-3 sm:grid-cols-3">
            <Card className="bg-blue p-4 text-black">
              <p className="text-[10px] font-black uppercase text-black/70">Original</p>
              <p className="text-2xl font-black">{formatBytes(originalBytes)}</p>
            </Card>
            <Card className="bg-green p-4 text-black">
              <p className="text-[10px] font-black uppercase text-black/70">Optimized</p>
              <p className="text-2xl font-black">{formatBytes(optimizedBytes)}</p>
            </Card>
            <Card className="bg-orange p-4 text-black">
              <p className="text-[10px] font-black uppercase text-black/70">Savings</p>
              <p className="text-2xl font-black">{savingsPercent}%</p>
            </Card>
          </div>

          <Card className="space-y-3 p-4">
            <Button
              className="w-full"
              variant="coral"
              onClick={() => {
                downloadTextFile("optimized.svg", activeSvg);
                toast.success("Optimized SVG downloaded");
              }}
            >
              <Download className="h-4 w-4" /> Download Optimized SVG
            </Button>
            <div className="flex flex-wrap gap-2">
              <CopyButton text={activeSvg} label="Copy SVG" className="flex-1" />
              <CopyButton
                text={result?.reactComponent || ""}
                label="Copy React Component"
                className="flex-1"
              />
            </div>
            <Button
              variant="white"
              className="w-full"
              onClick={() => {
                if (!result?.reactComponent) {
                  toast.error("Optimize first to generate React component");
                  return;
                }
                downloadTextFile("optimized-svg.tsx", result.reactComponent);
                toast.success("React component downloaded");
              }}
            >
              <FileCode2 className="h-4 w-4" /> Download React Component
            </Button>
          </Card>
        </div>
      </div>

      <Card className="overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b-[3px] border-black bg-slate-900 px-4 py-3">
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant={outputMode === "svg" ? "yellow" : "dark"}
              onClick={() => setOutputMode("svg")}
            >
              SVG Output
            </Button>
            <Button
              size="sm"
              variant={outputMode === "react" ? "yellow" : "dark"}
              onClick={() => setOutputMode("react")}
            >
              React Component
            </Button>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="blue">{result ? "Optimized" : "Waiting"}</Badge>
            <CopyButton
              text={outputMode === "svg" ? activeSvg : result?.reactComponent || ""}
              label="Copy Output"
            />
          </div>
        </div>

        <CodeEditor
          value={
            outputMode === "svg"
              ? activeSvg
              : result?.reactComponent || "// Optimize SVG to generate React component"
          }
          onChange={() => {}}
          language={outputMode === "svg" ? "xml" : "typescript"}
          height="360px"
        />
      </Card>

      <Card className="p-4">
        <p className="text-sm font-bold text-slate-200">
          {result
            ? `Optimization complete. Reduced ${formatBytes(originalBytes)} to ${formatBytes(optimizedBytes)} in ${elapsedMs}ms.`
            : "Paste an SVG or upload a file, tune options, and run optimization to generate production-ready output."}
        </p>
        <Button
          variant="green"
          className="mt-3"
          onClick={() => void optimizeSvg()}
          disabled={loading}
        >
          {loading ? <LoadingSpinner /> : <Sparkles className="h-4 w-4" />} Run Optimization
        </Button>
      </Card>
    </div>
  );
}
